services:
  authserviceapi:
    build:
      context: .
      dockerfile: src/AuthService/AuthService.API/Dockerfile
      args:
        - configuartion=Debug
    container_name: authserviceapi
    ports:
      - "8080:5000"
      - "8081:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - expense-network
    depends_on:
      - expense-db
    healthcheck:
      test: curl -f -k http://localhost:5000/health || curl -f -k https://localhost:5001/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
    expense-network:
        driver: bridge

volumes:
    sqlserver_data:
        driver: local