services:
  authserviceapi:
    image: ${DOCKER_REGISTRY-}authserviceapi
    build:
      context: .
      dockerfile: src/AuthService/AuthService.API/Dockerfile
    container_name: authserviceapi
    networks:
      - expense-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # expense-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: expense-db
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=Root123#
  #     - TZ=UTC
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql
  #   networks:
  #     - expense-network
  #   healthcheck:
  #     test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Root123#" -Q "SELECT 1" -b -o /dev/null
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

volumes:
  sqlserver_data:
    driver: local

networks:
  expense-network:
    driver: bridge
